### ISSUE TITLE
RFE: don't pin dependencies exactly

### ISSUE THREAD

**Issue by jonathanunderwood** [sivakov512/python-markdown-full-yaml-metadata#13]
This extension pins every dependency exactly. That's a fine strategy for an end-user application, but for a library it's not really the right thing to do, as you inevitably end up with conflicting dependencies in a project that consumes the library. Please would you consider having more liberal dependencies (eg. markdown>3.0, rather than markdown==3.0.1) for example.

Thanks for a great extension, by the way!

**Comment by sivakov512** [comment]
Oh, sorry for this.
Can you make PR with this fix? After this I will make a new release

**Comment by jonathanunderwood** [comment]
I'll look into it - unfortunately as it is work related, I'll have to obtain legal sign-off to submit a PR, which will slow things down.

**Comment by sivakov512** [comment]
Okay, I will help you

**Comment by sivakov512** [comment]
This issue and #14 are fixed in 1.10 release (already published)
Please start this repo if you want to say "thank you"
