### ISSUE TITLE
Move setup_requires to pyproject.yaml

### ISSUE THREAD

**Issue by jonathanunderwood** [sivakov512/python-markdown-full-yaml-metadata#14]
When build system (setuptools) requirements are specified in setup.py, they end up being installed by distutils, even when pip installing. Because distutils is bit-rotting, it doesn't work with system installed openssl. 

Locally, for me, that means distutils doesn't know about some SSL CA certs, and as such, a `pip install markdown-full-yaml-metadata` will fail when trying to install `setuptools_markdown` due to being unable to validate the SSL cert (I am behind a coorporate proxy which MITMs all traffic and resigns with a local cert).

Moving the `setup_requires` deps to `pyproject.toml` fixes this - I suggest something like this:

```
[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools>=36.6", "setuptools_markdown", "wheel",]
build-backend = "setuptools.build_meta"
```

**Comment by sivakov512** [comment]
Looks like [setuptools_markdown](https://github.com/sivakov512/python-markdown-full-yaml-metadata/blob/master/setup.py#L23) is not required for installation - some time ago I started using `long_description_content_type="text/markdown"`, but forgot to remove `setup_requires`.
Will your problem be fixed if I remove this dep?

**Comment by jonathanunderwood** [comment]
That'd also fix it, yes :)

**Comment by sivakov512** [comment]
I think you can create a PR for #13 and fix this problem too. Are you ok with this?

**Comment by jonathanunderwood** [comment]
Unfortunately, this doesn't quite fix things, as `setup.py` still has a `setup_requires` entry, for `pytest-runner` now. To fix this, I suggest adding the following to `pyproject.toml`:

```
[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools>=36.6", "pytest-runner", "wheel",]
build-backend = "setuptools.build_meta"
```

and removing `setup_requires` from `setup.py`.

**Comment by sivakov512** [comment]
After this changes `python setup.py test` will fail. Can you provide more info about suggested changes?

**Comment by jonathanunderwood** [comment]
Hm That's true. You'd need to `pip install pytest` and `pytest` directly. I understand that running of subcommands via setup.py is something that'll go away moving forward anyway. There's a way to fix this which satisfies the desire to keep `python setup.py test` still working, though, along the lines of:

```
import sys

...
needs_pytest = {'pytest', 'test', 'ptr'}.intersection(sys.argv)
pytest_runner = ['pytest-runner'] if needs_pytest else []

setup(
...
setup_requires=pytest_runner,
...
)

**Comment by sivakov512** [comment]
It looks like a bad solution.
How do you install it? I try to install this lib via pip and as "install requires" in setup.py and does not see installation of pytest-runner.
I can't reproduce it.

**Comment by jonathanunderwood** [comment]
Not sure I understand the question.

`pip install python-markdown-full-yaml-metadata` should install the plugin, PyYAML and Markdown, but not pytest-runner.

`python setup.py test` should download `pytest_runner` and run the tests.

Which doesn't work?

**Comment by sivakov512** [comment]
Yes, that's true. I mean that I don't understand your problem with "setup_requires". What are the steps to reproduce your problem?

**Comment by jonathanunderwood** [comment]
See the description at the top. Unfortunately, to reproduce it you'd need to be behind a corporate proxy that requires you add an extra CA cert to your trust store. The problem is that distutils doesn't support that, and it's distutils that is invoked to install the setup_requires deps. Hence, behind a corp proxy, or if using a local mirror of pypi, a `pip install python-markdown-full-yaml-metadata` fails at the point distutils is invoked to install the `setup_requires` dependencies.

**Comment by ol-lo** [comment]
@jonathanunderwood 

Could you say please? How do you exactly do install the package? What command do you run?:
- pip install
- setup.py install
- maybe something other?

**Comment by jonathanunderwood** [comment]
`pip install python-markdown-full-yaml-metadata`

**Comment by sivakov512** [comment]
Oh, now I understand how the problem happens. I'll think about it and come back with a solution a bit later.

For now you can use version 1.1.0 - it should work correctly for you, but depending on the version of PyYAML ​​installed, it may produce warnings.

**Comment by jonathanunderwood** [comment]
> Oh, now I understand how the problem happens. I'll think about it and come back with a solution a bit later.

What's wrong with the fix to setup.py I posted above?

**Comment by sivakov512** [comment]
I'm not sure this is a good solution. I would like the setup to always work the same.

Also it still seems wrong to me to require pytest-runner if the user just wants to install it

**Comment by jonathanunderwood** [comment]
> I'm not sure this is a good solution. I would like the setup to always work the same.
> 
> Also it still seems wrong to me to require pytest-runner if the user just wants to install it

Both of those are achieved with the change to the setup.py I outlined above.
